### ISSUE TITLE
Move to incubator

### ISSUE THREAD

**Issue by blond** [bem-incubator/stat-counters#31]
https://github.com/bem-incubator

- [x] Нажать кнопку и перенести проект;
- [x] Переименовать вхождения в файлах #40 ;
- [x] Убедиться что тревисы и коверолсы не отвалились;

**Comment by zxqfox** [comment]
@blond у тебя есть туда доступ?

@remnev ты до сих пор против? ;)

**Comment by blond** [comment]
@zxqfox доступ есть.

@remnev почему против?

**Comment by remnev** [comment]
@all, а что в bem совсем никак?
 Если никак, то идем в инкубатор. Просто инкубатор подразумевает, что из него надо куда-то вырасти. Например, в bem

**Comment by voischev** [comment]
Инкубатор отличное место. Только вот без админских прав туда не пускают :)

**Comment by tadatuta** [comment]
отправил инвайт @remnev

**Comment by sameoldmadness** [comment]
Как смотрите на то, чтобы переименовать репозиторий в bem-stat-counters?

Ну, для поддержания единообразия.

**Comment by remnev** [comment]
Я за.

**Comment by remnev** [comment]
Тревисы и коверолсы не отвалились.

**Comment by zxqfox** [comment]
bem-counters хуже?

**Comment by remnev** [comment]
Мы уже есть в bower как bem-stat-counters. bem-counters очень ширикое понятие, мы же только про счетчики статистики :)

**Comment by zxqfox** [comment]
Тогда да, :+1:
